import { Driver }  from './driver';

export var MOCK_DRIVERS: Driver[] = [{"drivername":"Driver1","password":"rr","ability":"Bicycle","firstname":"Anthony","lastname":"Ferlazzo","email":"aferlazzo@gmail.com","address":"5558 W. Shady Grove Drive","city":"Tucson","state":"AZ","zip":"85742","phone":"9253995359","selected":false},{"drivername":"Rocky","password":"rrr","ability":"Scooter","firstname":"Rocky","lastname":"Balboa","email":"rocky@movie.comq","address":"111 Hollywood Dr","city":"Hollywood","state":"CA","zip":"94321","phone":"310-999-1212","selected":false},{"drivername":"RockyII","password":"www","ability":"Motorcycle","firstname":"Slyvester","lastname":"Stallone","email":"sly@movies.com","address":"77 Sunset Strip","city":"Los Angeles","state":"CA","zip":"93333","phone":"818-555-1212","selected":false},{"drivername":"Recruiter","password":"pp","ability":"Bicycle","firstname":"Rocky","lastname":"Racoon","email":"rocky@music.org","address":"99 Tears","city":"Anywhere","state":"AL","zip":"000000","phone":"888-999-0000","selected":false},
  {"drivername":"Mary","password":"aa","ability":"Truck","firstname":"Mary","lastname":"Marples","email":"mary@hightech.com","address":"444 Sand Hill Drive","city":"Palo Alto","state":"CA","zip":"94466","phone":"615-888-6666","selected":false},
  {"drivername":"Tony","password":"aa","ability":"Car (stick)","firstname":"Tony","lastname":"Ferlazzo","email":"aferlazzo@gmail.com","address":"5558 W. Shady Grove Drive","city":"Castro Valley","state":"CA","zip":"85742","phone":"19253995359","selected":false},
  {"drivername":"Recruiter","password":"kk","ability":"Car (automatic)","firstname":"Anthony","lastname":"Ferlazzo","email":"aferlazzo@gmail.com","address":"5558 W. Shady Grove Drive","city":"Tucson","state":"AZ","zip":"85742","phone":"19253995359","selected":false},
  {"drivername":"Mr.Ed","password":"pll","ability":"Motorcycle","firstname":"Ed","lastname":"Norton","email":"ed2haytown.net","address":"42 Universal Ave","city":"Slippery Rock","state":"AR","zip":"33221","phone":"406-321-7878","selected":false},
  {"drivername":"missy","password":"ee","ability":"Bicycle","firstname":"Missy","lastname":"Bagwell","email":"missy@aol.com","address":"55 Cornwell Blvd","city":"Santa Ana","state":"CA","zip":"93210","phone":"718-222-1212","selected":false},
  {"drivername":"Willie","password":"ss","ability":"Car (automatic)","firstname":"Bill","lastname":"MyDeskMate","email":"bill@ge,com","address":"888 Altamont Pass","city":"Tracy","state":"CA","zip":"98765","phone":"654-909-8888","selected":false},
  {"drivername":"TheRock","password":"hhh","ability":"Bicycle","firstname":"Divya","lastname":"MyLunchBuddy","email":"divya@ge.com","address":"35 Restmore","city":"San Ramon","state":"CA","zip":"94583","phone":"925-555-1212","selected":false},
  {"drivername":"Matthew","password":"ppp","ability":"Truck","firstname":"Matthew","lastname":"Tangerine","email":"matt@cactusgarden.org","address":"777 Thornydale Circle","city":"Sun City","state":"AZ","zip":"88843","phone":"520-987-0000","selected":false},
  {"drivername":"Bryant","password":"ttt","ability":"Car (automatic)","firstname":"Bryant","lastname":"Stevenson","email":"bryant@baseball.mlb","address":"511 College Try Road","city":"Empire","state":"NC","zip":"12341","phone":"443-487-3322","selected":false},
  {"drivername":"Paulie","password":"pp","ability":"Car (stick)","firstname":"Paul","lastname":"Youola","email":"paulie@penmenship.com","address":"22 Radio Tower Road","city":"Sunnyvale","state":"CA","zip":"94433","phone":"408-665-4321","selected":false},
  {"drivername":"Lavanya","password":"pp","ability":"Car (automatic)","firstname":"Lavanya","lastname":"LaBounski","email":"lucky@ge.com","address":"900 Newton","city":"Ironhorse Trail","state":"CA","zip":"94581","phone":"765-432-9908","selected":false},
  {"drivername":"Munster","password":"gooey","ability":"Truck","firstname":"Herman","lastname":"Munster","email":"herman@tvshow.com","address":"1313 Mockingbird Lane","city":"Los Angeles","state":"CA","zip":"91221","phone":"310-666-5432","selected":false},
  {"drivername":"Zedman","password":"77777","ability":"Car (automatic)","firstname":"Floey","lastname":"Zedman","email":"floey@colonel-airlines.com","address":"147 Giffords Lane","city":"Staten Island","state":"NY","zip":"10308","phone":"212-555-1212","selected":false}];

